### ISSUE TITLE
Add screenshots & instructions for starting the client

### ISSUE THREAD

**Issue by jacc** [TeamCernodile/Botcord#16]
Could be helpful.

**Comment by DoctorDarkMagic** [comment]
jacccccc

**Comment by DoctorDarkMagic** [comment]
speak to me young one

**Comment by jacc** [comment]
Email me (look at profile)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DoctorDarkMagic** [comment]
answer me then ;(

**Comment by cernodile** [comment]
This project is discontinued, there's no point in making issues and having conversations in them.
