### ISSUE TITLE
Hacktoberfestie!

### ISSUE THREAD

**Issue by cernodile** [TeamCernodile/Botcord#2]
Want to participate in Hacktoberfest? We got you covered!

In order for you to take credit for this issue, I'm giving you a task of making the home page more beautiful, and make it **actualy** introduce Botcord.
Please note, that you must **not** remove the functionality of enter token, not modify initial.js unless you add a new interactable feature.

Go ahead, surprise us!
- Team Cernodile

**Comment by jakehasler** [comment]
I'll claim this one!

**Comment by anabastos** [comment]
#3
