### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by zZ0MBi3** [TeamCernodile/Botcord#5]
uh, how do i use this? do i have to compile it or something? cuz i dunno how

**Comment by cernodile** [comment]
Hello! Thank you for your interest in Botcord, this repository is as of currently outdated. Simply download contents of the "client" folder, and put it to your webserver to reach it.
If that's not an option, you could use the public demo (with latest bleeding edge features) at https://demo.cernodile.com/botcord/

For more assistance, check out [our Discord server](https://discord.gg/ZKA7sE8), and don't be afraid to ask us!

- Cernodile

**Comment by zZ0MBi3** [comment]
now its stuck at resuming last session
