### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Nikitaw99** [TeamCernodile/Botcord#6]
Just wanted to try it out on the demo website you host, but upon entering my bot's token, nothing happens.

There is no `submit` button, even.

**Comment by cernodile** [comment]
Did you press "enter"? Are you sure your token is valid?

**Comment by cernodile** [comment]
It works same way you send a Discord message, no submit button intended.

**Comment by Nikitaw99** [comment]
I did press enter, but it just inserted a newline and thats it.

**Comment by cernodile** [comment]
Please open `Ctrl+Shift+I` or `F12` developer tools, go to console, and reply with any error you recieve.

**Comment by Nikitaw99** [comment]
![teh errors](http://i.imgur.com/ahx6dZ0.png)

**Comment by cernodile** [comment]
Browser, operating system?

**Comment by cernodile** [comment]
Also, join https://discord.gg/ZKA7sE8 for faster and easier assitance.

**Comment by Nikitaw99** [comment]
I am using Firefox 50 on Windows 7.

**Comment by cernodile** [comment]
I don't think Discord.js webpack is meant for that old js that FF has. Try chrome?
