### ISSUE TITLE
Add twemoji parsing 

### ISSUE THREAD

**Issue by SnazzyPine25** [TeamCernodile/Botcord#8]
https://github.com/twitter/twemoji/blob/gh-pages/README.md  
`twemoji.parse("content")` will easily parse any emojis and convert them.

**Comment by cernodile** [comment]
It doesn't seem to parse the emojis inside colons, though. How would we go around fixing that? We can't just do it manually, can we?

**Comment by SnazzyPine25** [comment]
Twemoji has a module for parsing http://twemoji.maxcdn.com/2/twemoji.min.js?2.2.3

**Comment by SnazzyPine25** [comment]
Heres something you can use to parse shortcode https://gist.github.com/SnazzyPine25/824a0befb240e80ece2506b95fd1309d

**Comment by cernodile** [comment]
Alright, I'll make something up, alongside update GitHub version with actual progress (abandoned JSCord, using minified d.js)

**Comment by cernodile** [comment]
Twemoji parsing is now added in the latest commits.
